
import Head from 'next/head'
import { Inter } from 'next/font/google'

import styles from './MainLayout.module.css'
import { Navbar } from '../Navbar'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

type MainLayoutProps = {
    children: ReactNode
}

export const MainLayout = ({children}: MainLayoutProps) => {

    return (
        <>
          <Head>
            <title>Home - Luis Penagos</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar /> 
    
          <main className={`${styles.main} ${inter.className}`}>

            { children }

          </main>
        </>
      )
}
